name: deploy service

on:
  push:
    branches:
      - main

jobs:
  ssh-agent: # Job 이름
    runs-on: ubuntu-24.04 # GitHub 워크스페이스 환경

    steps: # 실행할 작업(step)
      - name: Checkout code
        uses: actions/checkout@v4

      # 캐시 하는 부분분
      - name: Set Up Cache Repo
        uses: actions/cache@v4.2.0
        with:
          path: /tmp/docker-cache # 캐시로 관리할 경로
          key: docker-cache-${{ github.sha }} # 불러올 캐시 이름(식별자)
          restore-keys: docker-cache- # 만약 캐시 key를 찾지못하면 대체할 캐시 key 패턴

      - name: Create .env file
        run: |
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env

      - name: Add Remote Server Fingerprint to Known Hosts
        run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts || true

      - name: Login DockerHub
        run: echo '${{ secrets.DOCKER_PASSWORD}}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      # 캐시 하는 부분
      # 빌드킷 설치치
      - name: Set up Docker Buildkit
        uses: docker/setup-buildx-action@v3
      # buildkit 빌더(이미지 생성 도구) 생성 & 설정정
      - name: Create buildkit 빌더
        run: docker buildx

      - name: Docker Image Build
        run: docker compose -f docker-compose-cache.yml build

      - name: Docker Image Push
        run: docker compose -f docker-compose-cache.yml push

      - name: Copy .env / docker-compose-cache.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose-cache.yml,.env"
          target: "~/github-actions-work-directory"

      - name: Pull Image & Up Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/github-actions-work-directory
            docker compose -f docker-compose-cache.yml pull
            docker compose -f docker-compose-cache.yml down
            docker compose -f docker-compose-cache.yml up -d
            docker system prune -f
